swagger: '2.0'
basePath: /api/2
consumes:
  - application/json
produces:
  - application/json
info:
  version: 2.0.0
  title: Project-FiFo
parameters:
  fulllistParam:
    name: full-list
    in: query
    description: Enables or disables the return ov objects rather then uuids
    required: false
    allowEmptyValue: false
    type: boolean
    format: boolean
  fulllistfieldsParam:
    name: full-list-fields
    in: query
    description: Fields to be returnd when full-list is enabled
    required: false
    format: string
    type: array
    items:
      type: string
    collectionFormat: csv
definitions:
  uuid:
    type: string
    pattern: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
  user:
    description: a user object
    type: object

paths:
  '/users':
    get:
      summary: Lists all users visible to the user
      description: |
        See Get User for the fields available for full-list-fields.
      parameters:
        - $ref: '#/parameters/fulllistParam'
        - $ref: '#/parameters/fulllistfieldsParam'
      responses:
        '200':
          description: list of users
          schema:
            type: array
            items:
              allOf:
                - $ref: '#/definitions/user'
                - $ref: '#/definitions/uuid'
    post:
      summary: Creates a new user
      description: |
        Creates a new user
      responses:
        303:
          description: Redirect to new user

  '/user/{uuid}':
    get:
      summary: read grouping
      parameters:
        - name: uuid
          in: path
          description: uuid of the grouping to get
          required: true
          type: string
      responses:
        '200':
          description: returns a grouping
          schema:
            $ref: '#/definitions/user'
  '/users/{uuid}':
    put:
      summary: Changes the password of a user
      parameters:
        - name: uuid
          in: path
          description: uuid of the user to modify
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              password:
                description: new password to set
                type: string
      responses:
        '200':
          description: OK
  '/users/{uuid}':
    delete:
      summary: Deletes a user
      parameters:
        - name: uuid
          in: path
          description: uuid of the user to delete
          required: true
          type: string
      responses:
        '200':
          description: OK
  '/user/{uuid}/permissions/{permission}':
    get:
      summary: |
        Tests if a user has is allowed to perform an action. 
        Please note that 403 here does not mean the user is not allowed 
        but that the requesting token was not allowed to test for the client!
      parameters:
        - name: uuid
          in: path
          description: UUID of the user
          required: true
          type: string
        - name: permission
          in: path
          description: |
            the permission to test as path i.e. 'some/funky/permission'
          required: true
          type: string
      responses:
        '200':
          description: OK
    put:
      summary: Grants a permission to a user
      parameters:
        - name: uuid
          in: path
          description: UUID of the user
          required: true
          type: string
        - name: permission
          in: path
          description: |
            the permission to grant as path i.e. 'some/funky/permission'
          required: true
          type: string
      responses:
        '200':
          description: OK
    delete:
      summary: Revokes a permission from a user
      parameters:
        - name: uuid
          in: path
          description: UUID of the user
          required: true
          type: string
        - name: permission
          in: path
          description: |
            the permission to revoke as path i.e. 'some/funky/permission'
          required: true
          type: string
      responses:
        '200':
          description: OK